User.destroy_all
Movie.destroy_all
puts "Seeding spices..."
User.create(username: "frank", email: "frank@gmail.com", password: "7654789")
User.create(username: "kev", email: "kev@gmail.com", password: "878965jk")
User.create(username: "monica", email: "monica@gmail.com", password: "54653tr")
User.create(username: "sharon", email: "sharon@gmail.com", password: "55478ry")
user1 = User.create(username: "tess", email: "tess@gmail.com", password: "56357df")
user2 = User.create(username: "Greg", email: "greg@gmail.com", password: "75675gj")
user3 = User.create(username: "Maureen", email: "maureen@gmail.com", password: "9887mr")
user4 = User.create(username: "Timothy", email: "timothy@gmail.com", password: "554fd")
user5 = User.create(username: "Meja", email: "meja@gmail.com", password: "meja1")
user6 = User.create(username: "Debbie", email: "Deb@gmail.com", password: "12325DB")
user7 = User.create(username: "Cynthia", email: "Cynthia@gmail.com", password: "CY123")
user8 = User.create(username: "Clement", email: "Clement@gmail.com", password: "Cl343")
user9 = User.create(username: "Diana", email: "diana@gmail.com", password: "D324")
user10 = User.create(username: "Keith", email: "keith@gmail.com", password: "7678KE")

Movie.create(title: "Ant-Man and the Wasp: Quantumania", description: "Scott Lang and Hope van Dyne, along with Hope's parents, Hank Pym and Janet van Dyne, and Scott’s daughter, Cassie, are accidentally sent to the Quantum Realm. The family soon finds themselves exploring the Quantum Realm, interacting with strange new creatures, characters that Janet previously encountered, and embarking on an adventure that will push them beyond the limits of what they thought was possible.", category: "Action", user_id: user1.id)
Movie.create(title: "Creed III", description: "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damian—a fighter who has nothing to lose.", category: "Action", user_id: user2.id)
Movie.create(title: "Jesus Revolution", description: "In the 1970s, young Greg Laurie is searching for all the right things in all the wrong places: until he meets Lonnie Frisbee, a charismatic hippie-street-preacher. Together with Pastor Chuck Smith, they open the doors of Smith’s languishing church to an unexpected revival of radical and newfound love, leading to what TIME Magazine dubbed a JESUS REVOLUTION.", category: "Drama", user_id: user3.id)
Movie.create(title: "Magic Mike’s Last Dance (2023)", description: "“Magic” Mike Lane takes to the stage again after a lengthy hiatus, following a business deal that went bust, leaving him broke and taking bartender gigs in Florida. For what he hopes will be one last hurrah, Mike heads to London with a wealthy socialite who lures him with an offer he can’t refuse and an agenda all her own. With everything on the line, once Mike discovers what she truly has in mind, will he—and the roster of hot new dancers he’ll have to whip into shape—be able to pull it off?", category: "Drama", user_id: user4.id)
Movie.create(title: "Demon Slayer: Kimetsu No Yaiba—To the Swordsmith Village (2023)", description: "After his family is viciously murdered, a young boy named Tanjiro Kamado joins the Demon Slayer Corps in hopes of turning his younger sister Nezuko back into a human. With every mission, Tanjiro grows stronger, along with his unwavering resolve to protect others. Together with his comrades, Zenitsu and Inosuke, along with one of the strongest members of the Demon Slayer Corps, Tengen Uzui, Tanjiro embarks on a mission within the Yoshiwara Entertainment District, where they encounter the formidable, high-ranking demons, Daki and Gyutaro, who had been inhabiting the city for many years. As a fierce battle rages on between the Corps members and the Upper Rank demons, all hope seems lost.", category: "Adventure", user_id: user5.id)
Movie.create(title: "Operation Fortune: Ruse de guerre", description: "Operation Fortune: Ruse de guerre (2022)", category: "Thriller", user_id: user6.id)
Movie.create(title: "Emancipation (2022)", description: "nspired by the true story of a man who would do anything for his family — and for freedom. When peter, an enslaved man, risks his life to escape and return to his family, he embarks on a perilous journey of love and endurance.", category: "Thriller", user_id: user7.id)
Movie.create(title: "80 for Brady (2023)", description: "Four best friends live life to the fullest when they take a wild trip to the 2017 Super Bowl LI to see their hero Tom Brady play.", category: "Comedy", user_id: user8.id)
Movie.create(title: "A Man Called Otto", description: "Based on the comical and moving New York Times bestseller, A Man Called Otto tells the story of Otto Anderson, a grumpy widower whose only joy comes from criticizing and judging his exasperated neighbors. When a lively young family moves in next door, he meets his match in quick-witted and very pregnant Marisol, leading to an unexpected friendship that will turn his world upside-down.", category: "Comedy", user_id: user9.id)
Movie.create(title: "M3GAN", description: "M3GAN is a marvel of artificial intelligence, a life-like doll programmed to be a child’s greatest companion and a parent’s greatest ally. Designed by brilliant toy-company roboticist Gemma, M3GAN can listen and watch and learn as she becomes friend and teacher, playmate and protector, for the child she is bonded to. When Gemma suddenly becomes the caretaker of her orphaned 8-year-old niece, Cady, Gemma’s unsure and unprepared to be a parent. Under intense pressure at work, Gemma decides to pair her M3GAN prototype with Cady in an attempt to resolve both problems—a decision that will have unimaginable consequences.", category: "Horror", user_id: user10.id)

puts "✅ Done seeding!"
